# Generated by Django 2.0.4 on 2018-04-17 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relative',
            name='spouse',
        ),
        migrations.AddField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relative',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_relatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relative',
            name='current_spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drive.Relative'),
        ),
        migrations.AddField(
            model_name='relative',
            name='spouses',
            field=models.ManyToManyField(blank=True, related_name='_relative_spouses_+', to='drive.Relative'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos_notes', to='drive.Photo'),
        ),
        migrations.AlterField(
            model_name='relative',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_relative', to=settings.AUTH_USER_MODEL),
        ),
    ]
