# Generated by Django 2.0.4 on 2018-04-18 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0002_auto_20180417_2315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.AlterField(
            model_name='relative',
            name='birth_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birthplace'),
        ),
    ]
